### ISSUE TITLE
Private repositories

### ISSUE THREAD

**Issue by kevb** [swarm-pack/swarm-pack#9]
I would like to define 1 or more "private repositories" which is a git repository with the same structure as the [official repository](https://github.com/swarm-pack/repository).

Repositories could be

1. Passed in CLI command
2. Passed into options in NPM package
3. Possibly configured in a config file?

Question 1 - would this mean we could remove ability to use individual git repo for packs? We could make everything a "repository" of sorts, with the same structure? Could make life easier...

Question 2 - currently the official repo has "stable" and "incubator" namespaces. Do we allow custom namespaces?

Question 3 - how do I refer to such packages? e.g. 

In configuration:
```
repositories:
  # This could be implicit
  - name: official
    url: https://github.com/swarm-pack/repository
  # Private
  - name: myrepo
    url: https://github.com/myorg/myrepo
```

And then to deploy:

```
swarm-pack deploy myrepo/stable/package prod
```

Do we then make the official repo use this format

```
swarm-pack deploy official/stable/package prod
```
